### ISSUE TITLE
AccessDenied. User doesn't have permission to call ssm:GetParameters 

### ISSUE THREAD

**Issue by devopscaxsol** [aws-samples/aws-cross-account-cicd-pipeline#38]
Hello,

Getting Error like above when code pipeline deploy stage start execution for cross account deploy.
![image](https://github.com/aws-samples/aws-cross-account-cicd-pipeline/assets/108056553/873ab184-01d3-4354-b381-5aa35305a398)
AnyOne have any idea...

**Comment by lemked** [comment]
Not a fix, but a workaround: open Parameter Store on the production account and create the parameter with name `/cdk-bootstrap/hnb659fds/version` and value `18` manually.

**Comment by devopscaxsol** [comment]
Have resolved this by adding policy access for ssm in cross account role.

**Comment by lemked** [comment]
Apologies, I confused this with a similar error. Documented the other error that my workaround here refers to [here](https://github.com/aws-samples/aws-cross-account-cicd-pipeline/issues/40).
